application: aoc
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js

- url: /.*
  script: aoc.py

